name: todo_app
description: todo app made by 271.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  sqflite: ^2.0.0
  intl: ^0.17.0
  conditional_builder_null_safety: ^0.0.6
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0
  sizer: ^2.0.15
  fluttertoast: ^8.0.9
  flutter_local_notifications: ^9.3.1
  timezone: ^0.8.0
  bottom_navy_bar: ^6.0.0
  device_preview: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true